language: python

matrix:
  include:
    - os: linux
      python: 2.7

    - os: osx
      language: generic
      env: PYTHON_VERSION=2.7.13

install:
  - "./.travis/install.sh"

script:
  - "./.travis/run.sh"